[general]
import = [
  "~/.config/alacritty/themes/dracula.toml",
  # "~/.config/alacritty/transparency.toml",
]

[font]
size = 11

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 40
y = 40
