vim.cmd("hi clear")
vim.cmd("syntax reset")
vim.g.colors_name = "alba"

vim.g.AlbaBlack = "#0f0a10"
vim.g.AlbaRed = "#ec8a8a"
vim.g.AlbaGreen = "#c4d89a"
vim.g.AlbaYellow = "#e8ce6c"
vim.g.AlbaBlue = "#a0c8e8"
vim.g.AlbaMagenta = "#cc90c0"
vim.g.AlbaCyan = "#88c8be"
vim.g.AlbaWhite = "#ffffff"
vim.g.AlbaGold = "#e8c882"
vim.g.AlbaGrey1 = "#1c151d"
vim.g.AlbaGrey2 = "#2e272f"
vim.g.AlbaGrey3 = "#403941"
vim.g.AlbaGrey4 = "#544d55"
vim.g.AlbaGrey5 = "#6a636b"
vim.g.AlbaGrey6 = "#827b83"
vim.g.AlbaGrey7 = "#9c959d"
vim.g.AlbaGrey8 = "#ccc5cd"
vim.g.AlbaOrange = "#ec9e68"
vim.g.AlbaPeach = "#ffecd8"
vim.g.AlbaPink = "#eca8bc"

local hl = vim.api.nvim_set_hl

hl(0, "@lsp.type.class", { fg = vim.g.AlbaGold })
hl(0, "@lsp.type.member.typescript", { fg = vim.g.AlbaPeach })
hl(0, "@lsp.type.property.typescript", { fg = vim.g.AlbaPeach })
hl(0, "@lsp.type.property.typescriptreact", { fg = vim.g.AlbaPeach })
hl(0, "@type", { fg = vim.g.AlbaPink })
hl(0, "@type.builtin", { fg = vim.g.AlbaPink })
hl(0, "@variable", { fg = vim.g.AlbaPeach })
hl(0, "Boolean", { fg = vim.g.AlbaPink })
hl(0, "Character", { fg = vim.g.AlbaPink })
hl(0, "CmpItemAbbrMatch", { fg = vim.g.AlbaWhite })
hl(0, "ColorColumn", { bg = vim.g.AlbaGrey3 })
hl(0, "Comment", { fg = vim.g.AlbaGrey6, italic = true })
hl(0, "Conceal", { fg = vim.g.AlbaGrey6 })
hl(0, "Conditional", { fg = vim.g.AlbaOrange })
hl(0, "Constant", { fg = vim.g.AlbaPink })
hl(0, "Cursor", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaWhite })
hl(0, "CursorColumn", { bg = vim.g.AlbaGrey3 })
hl(0, "CursorLine", { bg = vim.g.AlbaGrey3 })
hl(0, "CursorLineFold", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "CursorLineNr", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaGrey2 })
hl(0, "CursorLineSign", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "Debug", { fg = vim.g.AlbaOrange })
hl(0, "Define", { fg = vim.g.AlbaOrange })
hl(0, "Delimiter", { fg = vim.g.AlbaPeach })
hl(0, "DiagnosticError", { fg = vim.g.AlbaRed })
hl(0, "DiagnosticHint", { fg = vim.g.AlbaPink })
hl(0, "DiagnosticInfo", { fg = vim.g.AlbaBlue })
hl(0, "DiagnosticUnderlineError", { sp = vim.g.AlbaRed, undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = vim.g.AlbaPink, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = vim.g.AlbaBlue, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = vim.g.AlbaGold, undercurl = true })
hl(0, "DiagnosticWarn", { fg = vim.g.AlbaGold })
hl(0, "DiffAdd", { bg = vim.g.AlbaGrey1 })
hl(0, "DiffChange", { bg = vim.g.AlbaGrey1 })
hl(0, "DiffDelete", { fg = vim.g.AlbaGrey2 })
hl(0, "DiffText", { bg = vim.g.AlbaGrey4 })
hl(0, "Directory", { fg = vim.g.AlbaOrange })
hl(0, "EndOfBuffer", { fg = vim.g.AlbaBlack })
hl(0, "Error", { fg = vim.g.AlbaRed, bg = vim.g.AlbaBlack })
hl(0, "ErrorMsg", { fg = vim.g.AlbaRed })
hl(0, "Exception", { fg = vim.g.AlbaOrange })
hl(0, "Float", { fg = vim.g.AlbaPink })
hl(0, "FloatBorder", { fg = vim.g.AlbaGrey3, bg = vim.g.AlbaBlack })
hl(0, "FloatTitle", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaBlack })
hl(0, "FoldColumn", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "Folded", { fg = vim.g.AlbaGrey7, bg = vim.g.AlbaGrey3 })
hl(0, "Function", { fg = vim.g.AlbaPeach })
hl(0, "FzfFloatBorder", { bg = vim.g.AlbaGrey1 })
hl(0, "FzfNormal", { bg = vim.g.AlbaGrey1 })
hl(0, "GitSignsAdd", { fg = vim.g.AlbaGreen, bg = vim.g.AlbaGrey1 })
hl(0, "GitSignsChange", { fg = vim.g.AlbaGrey5, bg = vim.g.AlbaGrey1 })
hl(0, "GitSignsDelete", { fg = vim.g.AlbaRed, bg = vim.g.AlbaGrey1 })
hl(0, "Identifier", { fg = vim.g.AlbaPeach })
hl(0, "Ignore", { fg = vim.g.AlbaGrey6 })
hl(0, "Include", { fg = vim.g.AlbaOrange })
hl(0, "Keyword", { fg = vim.g.AlbaOrange })
hl(0, "Label", { fg = vim.g.AlbaPeach })
hl(0, "LineNr", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "Macro", { fg = vim.g.AlbaOrange })
hl(0, "MatchParen", { fg = vim.g.AlbaGold })
hl(0, "ModeMsg", { fg = vim.g.AlbaGrey8 })
hl(0, "MoreMsg", { fg = vim.g.AlbaPink })
hl(0, "MsgArea", { fg = vim.g.AlbaGrey8 })
hl(0, "NonText", { fg = vim.g.AlbaGrey5, italic = true })
hl(0, "Normal", { fg = vim.g.AlbaPeach, bg = vim.g.AlbaBlack })
hl(0, "NormalFloat", { fg = vim.g.AlbaWhite, bg = vim.g.AlbaBlack })
hl(0, "Number", { fg = vim.g.AlbaPink })
hl(0, "Operator", { fg = vim.g.AlbaOrange })
hl(0, "Pmenu", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "PmenuMatch", { fg = vim.g.AlbaWhite, bg = vim.g.AlbaGrey2 })
hl(0, "PmenuSel", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaGrey2 })
hl(0, "PreProc", { fg = vim.g.AlbaOrange })
hl(0, "Question", { fg = vim.g.AlbaGold })
hl(0, "QuickFixLine", { bg = vim.g.AlbaGrey3 })
hl(0, "Repeat", { fg = vim.g.AlbaOrange })
hl(0, "Search", { bg = vim.g.AlbaOrange })
hl(0, "SignColumn", { bg = vim.g.AlbaGrey1 })
hl(0, "Special", { fg = vim.g.AlbaPeach })
hl(0, "SpecialChar", { fg = vim.g.AlbaGold })
hl(0, "SpecialComment", { fg = vim.g.AlbaPeach })
hl(0, "SpecialKey", { fg = vim.g.AlbaGrey7 })
hl(0, "SpellBad", { fg = vim.g.AlbaRed, undercurl = true })
hl(0, "SpellCap", { fg = vim.g.AlbaGold, undercurl = true })
hl(0, "SpellLocal", { fg = vim.g.AlbaPink, undercurl = true })
hl(0, "SpellRare", { fg = vim.g.AlbaPeach, undercurl = true })
hl(0, "Statement", { fg = vim.g.AlbaOrange })
hl(0, "StatusLine", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaGrey1 })
hl(0, "StatusLineNC", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "StorageClass", { fg = vim.g.AlbaOrange })
hl(0, "String", { fg = vim.g.AlbaGold })
hl(0, "Structure", { fg = vim.g.AlbaOrange })
hl(0, "TabLine", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "TabLineFill", { bg = vim.g.AlbaGrey1 })
hl(0, "TabLineSel", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaGrey2 })
hl(0, "Tag", { fg = vim.g.AlbaGold })
hl(0, "TermCursor", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaWhite })
hl(0, "TermCursorNC", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaGrey6 })
hl(0, "Title", { fg = vim.g.AlbaOrange, bold = true })
hl(0, "Todo", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaGold })
hl(0, "Type", { fg = vim.g.AlbaPink })
hl(0, "Typedef", { fg = vim.g.AlbaOrange })
hl(0, "Underlined", { fg = vim.g.AlbaGold, underline = true })
hl(0, "VertSplit", { fg = vim.g.AlbaGrey5, bg = vim.g.AlbaGrey1 })
hl(0, "Visual", { bg = vim.g.AlbaGrey3 })
hl(0, "WarningMsg", { fg = vim.g.AlbaOrange })
hl(0, "WildMenu", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaGrey8 })
hl(0, "WinBar", { fg = vim.g.AlbaGrey8, bg = vim.g.AlbaGrey1 })
hl(0, "WinBarNC", { fg = vim.g.AlbaGrey6, bg = vim.g.AlbaGrey1 })
hl(0, "WinSeparator", { fg = vim.g.AlbaGrey2, bg = vim.g.AlbaGrey1 })
hl(0, "gitignoreNegation", { fg = vim.g.AlbaPink })
hl(0, "htmlEndTag", { fg = vim.g.AlbaOrange })
hl(0, "htmlSpecialTagName", { fg = vim.g.AlbaOrange })
hl(0, "htmlTag", { fg = vim.g.AlbaWhite })
hl(0, "htmlTagN", { fg = vim.g.AlbaOrange })
hl(0, "htmlTagName", { fg = vim.g.AlbaOrange })
hl(0, "jsonKeyword", { fg = vim.g.AlbaOrange })
hl(0, "jsonString", { fg = vim.g.AlbaGold })
hl(0, "lCursor", { fg = vim.g.AlbaBlack, bg = vim.g.AlbaWhite })
hl(0, "markdownH1", { fg = vim.g.AlbaOrange })
hl(0, "markdownH2", { fg = vim.g.AlbaOrange })
hl(0, "markdownH3", { fg = vim.g.AlbaOrange })
hl(0, "markdownH4", { fg = vim.g.AlbaOrange })
hl(0, "markdownH5", { fg = vim.g.AlbaOrange })
hl(0, "markdownH6", { fg = vim.g.AlbaOrange })
hl(0, "mkdHeading", { fg = vim.g.AlbaOrange })
hl(0, "netrwClassify", { fg = vim.g.AlbaOrange })
hl(0, "tsxAttrib", { fg = vim.g.AlbaWhite })
hl(0, "tsxCloseString", { fg = vim.g.AlbaWhite })
hl(0, "tsxTagName", { fg = vim.g.AlbaGold })
hl(0, "typescriptES6SetProp", { fg = vim.g.AlbaPeach })
hl(0, "typescriptFuncCallArg", { fg = vim.g.AlbaPeach })
hl(0, "typescriptIdentifier", { fg = vim.g.AlbaPeach })
