return {
  "stevearc/conform.nvim",
  opts = {
    default_format_opts = { lsp_format = "fallback" },
    formatters_by_ft = {
      bash = { "beautysh" },
      css = { "prettierd" },
      go = { "goimports" },
      html = { "prettierd" },
      java = { "google-java-format" },
      javascript = { "biome-check", "prettierd" },
      javascriptreact = { "biome-check", "prettierd" },
      json = { "prettierd" },
      lua = { "stylua" },
      markdown = { "prettierd" },
      scss = { "prettierd" },
      sh = { "beautysh" },
      sql = { "sql_formatter" },
      typescript = { "biome-check", "prettierd" },
      typescriptreact = { "biome-check", "prettierd" },
      yaml = { "biome-check", "prettierd" },
      zsh = { "beautysh" },
    },
  },
}
